"""MkDocs hooks: sync Buildkite raw JSON into data/results, then regenerate charts.

Uses on_startup (not on_pre_build) so writes under docs/assets/charts/ do not
re-trigger livereload in an endless loop; generate_charts updates generated_at every run.

Also regenerates docs/reports/index.md so daily reports committed by external
pipelines (YYYY-MM-DD.md) are indexed automatically without editing mkdocs.yml.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

_REPORT_NAME_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")

# (model_name subdirectory under data/results/, keyword matching path or basename under buildkite_nightly_raw)
_BUILDKITE_RAW_SYNCS: tuple[tuple[str, str], ...] = (
    ("qwen3omni", "qwen3_omni"),
    ("qwen3tts", "qwen3_tts"),
    ("qwen_image", "qwen_image"),
    ("qwen_image_edit", "qwen_image_edit"),
    ("qwen_image_edit_2509", "qwen_image_edit_2509"),
    ("qwen_image_edit_2511", "qwen_image_edit_2511"),
    ("wan22", "wan22"),
    ("hunyuan_image3", "hunyuan_image3"),
    ("bagel", "bagel"),
    ("voxcpm2", "voxcpm2"),
)

_LOCAL_RAW_SYNCS: tuple[tuple[str, str], ...] = (
    ("hunyuan_image3", "hunyuan_image"),
)


def _run_sync(repo_root: Path, sync_script: Path, model_name: str, model_keywords: str, raw_root: Path | None = None) -> None:
    cmd = [
        sys.executable,
        str(sync_script),
        "--model-name",
        model_name,
        "--model-keywords",
        model_keywords,
    ]
    if raw_root is not None:
        cmd.extend(["--raw-root", str(raw_root)])
    proc = subprocess.run(
        cmd,
        cwd=str(repo_root),
        check=False,
    )
    if proc.returncode != 0:
        raise RuntimeError(
            f"sync_buildkite_raw_model_results.py ({model_name}) exited with status {proc.returncode}",
        )


def build_reports_index(reports_dir: Path) -> str:
    """Markdown for the reports archive page, linking every YYYY-MM-DD.md newest first."""
    names = sorted(
        (path.stem for path in reports_dir.glob("*.md") if _REPORT_NAME_RE.match(path.stem)),
        reverse=True,
    )
    lines = [
        "# Reports",
        "",
        "Daily reports are generated by an external pipeline and archived in this directory.",
        "This index is regenerated automatically at build time; newest first.",
        "",
    ]
    lines.extend(f"- [{name}]({name}.md)" for name in names)
    if not names:
        lines.append("_No reports archived yet._")
    return "\n".join(lines) + "\n"


def regenerate_reports_index(repo_root: Path) -> None:
    reports_dir = repo_root / "docs" / "reports"
    if not reports_dir.is_dir():
        return
    index_path = reports_dir / "index.md"
    content = build_reports_index(reports_dir)
    # Write only on change to avoid needless livereload churn.
    if not index_path.exists() or index_path.read_text(encoding="utf-8") != content:
        index_path.write_text(content, encoding="utf-8")


def on_startup(command: str, dirty: bool, **kwargs) -> None:
    repo_root = Path(__file__).resolve().parent.parent
    sync_script = repo_root / "scripts" / "sync_buildkite_raw_model_results.py"
    for model_name, model_keywords in _BUILDKITE_RAW_SYNCS:
        _run_sync(repo_root, sync_script, model_name, model_keywords)

    local_raw_root = repo_root / "data" / "local_nightly_raw"
    for model_name, model_keywords in _LOCAL_RAW_SYNCS:
        _run_sync(repo_root, sync_script, model_name, model_keywords, local_raw_root)

    gen_script = repo_root / "scripts" / "generate_charts.py"
    proc = subprocess.run(
        [sys.executable, str(gen_script)],
        cwd=str(repo_root),
        check=False,
    )
    if proc.returncode != 0:
        raise RuntimeError(f"generate_charts.py exited with status {proc.returncode}")

<<<<<<< HEAD
    report_sync = repo_root / "scripts" / "sync_nightly_test_reports.py"
    proc = subprocess.run(
        [sys.executable, str(report_sync)],
        cwd=str(repo_root),
        check=False,
    )
    if proc.returncode != 0:
        raise RuntimeError(f"sync_nightly_test_reports.py exited with status {proc.returncode}")
=======
    regenerate_reports_index(repo_root)
>>>>>>> d949b7d96829688b38a496fd832960a937c00af1
